import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('opt-in probe only accepts a current foreground paint and preserves full aggregates',async()=>{
  let time=1,sequence=0,focus=true,visible=true,longTasks;
  const frames=new Map(),listeners=new Map();
  const root={isConnected:true,token:'1',getAttribute(){return this.token;},getClientRects(){return visible?[{}]:[];}};
  const old=Object.fromEntries(['window','document','Element','requestAnimationFrame','cancelAnimationFrame','PerformanceObserver','getComputedStyle','performance'].map(key=>[key,Object.getOwnPropertyDescriptor(globalThis,key)]));
  const set=(key,value)=>Object.defineProperty(globalThis,key,{value,configurable:true,writable:true});
  set('Element',class {closest(){return this;}});
  set('document',{visibilityState:'visible',hasFocus:()=>focus,getElementById:()=>root,
    addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)});
  set('window',{addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:name=>listeners.delete(name)});
  set('performance',{now:()=>time});
  set('requestAnimationFrame',fn=>{const id=++sequence;frames.set(id,fn);return id;});
  set('cancelAnimationFrame',id=>frames.delete(id));
  set('getComputedStyle',()=>({visibility:'visible'}));
  set('PerformanceObserver',class {constructor(callback){longTasks=callback;}observe(){}disconnect(){}});
  const frame=()=>{time+=16;const batch=[...frames.values()];frames.clear();for(const fn of batch)fn(time);};
  try {
    const source=await readFile(new URL('../../../../wwwroot/performance-probe.js',import.meta.url),'utf8');
    const probe=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
    const guard={rootId:'note',attribute:'data-token',token:'1'};
    const count=kind=>JSON.parse(probe.report()).summary[kind]?.count??0;
    probe.start();
    const query='recordsQueryToPaintOpportunity',phaseKinds=['recordsQueryListHttp','recordsQueryCollectionHttp','recordsQueryApplyToChildrenReady'];
    const phases={listHttpMs:11,collectionHttpMs:22,applyToChildrenReadyMs:33};
    probe.end(probe.begin(query),true,guard,phases);
    frame();assert.ok(phaseKinds.every(kind=>count(kind)===0));
    frame();assert.ok(phaseKinds.every(kind=>count(kind)===1));
    const successful=JSON.parse(probe.report());
    phaseKinds.forEach((kind,index)=>assert.deepEqual(successful.samples[kind],[11*(index+1)]));
    const phaseCounts=()=>phaseKinds.map(count);
    probe.end(probe.begin(query),false,guard,phases);frame();frame();assert.deepEqual(phaseCounts(),[1,1,1]);
    probe.end(probe.begin(query),true,guard,phases);frame();root.token='2';frame();root.token='1';assert.deepEqual(phaseCounts(),[1,1,1]);
    probe.end(probe.begin(query),true,guard,phases);frame();focus=false;frame();focus=true;assert.deepEqual(phaseCounts(),[1,1,1]);
    const obsolete=probe.begin(query);listeners.get('compositionstart')({type:'compositionstart',target:new Element()});
    probe.end(obsolete,true,guard,phases);frame();frame();assert.deepEqual(phaseCounts(),[1,1,1]);
    for(const invalid of [NaN,Infinity,-1,'12',null,undefined]){
      probe.end(probe.begin(query),true,guard,{...phases,collectionHttpMs:invalid});frame();frame();
      assert.deepEqual(phaseCounts(),[1,1,1]);
    }
    probe.end(probe.begin('other-span'),true,guard,phases);frame();frame();assert.deepEqual(phaseCounts(),[1,1,1]);
    probe.end(probe.begin(query),true,null,phases);frame();frame();assert.deepEqual(phaseCounts(),[1,1,1]);
    // Valid end-to-end samples survive malformed diagnostics; no phase changes its gate.
    assert.equal(count(query),8);
    probe.end(probe.begin('rendered'),true,guard);frame();frame();assert.equal(count('rendered'),1);
    probe.end(probe.begin('rejected'),false,guard);frame();frame();assert.equal(count('rejected'),0);
    probe.end(probe.begin('changed-token'),true,guard);frame();root.token='2';frame();assert.equal(count('changed-token'),0);root.token='1';
    probe.end(probe.begin('hidden'),true,guard);frame();visible=false;frame();assert.equal(count('hidden'),0);visible=true;
    probe.end(probe.begin('background'),true,guard);frame();document.visibilityState='hidden';frame();assert.equal(count('background'),0);document.visibilityState='visible';
    probe.end(probe.begin('lost-focus'),true,guard);frame();focus=false;frame();assert.equal(count('lost-focus'),0);focus=true;
    const typing=probe.begin('new-input');
    listeners.get('beforeinput')({type:'beforeinput',target:new Element()});
    probe.end(typing,true,guard);frame();frame();assert.equal(count('new-input'),0);
    const composing=probe.begin('ime');
    listeners.get('compositionstart')({type:'compositionstart',target:new Element()});
    probe.end(composing,true,guard);frame();frame();assert.equal(count('ime'),0);
    probe.end(probe.begin('restarted'),true,guard);frame();probe.start();frame();frame();assert.equal(count('restarted'),0);
    const editKind='editorEditToCommittedVisible';
    const edit=(noteId='private-note-id',revision=1,composing=false)=>listeners.get('grasp-editor-edit')({detail:{noteId,revision,composing}});
    edit();const editedAt=time;time+=180+250; // debounce and durable draft preparation precede C# begin
    assert.equal(probe.beginEditorEdit('wrong-note',1),0);
    assert.equal(probe.beginEditorEdit('private-note-id',2),0);
    const editSpan=probe.beginEditorEdit('private-note-id',1);assert.ok(editSpan);
    assert.equal(probe.beginEditorEdit('private-note-id',1),0,'one edit is consumed once');
    probe.end(editSpan,true,guard);frame();assert.equal(count(editKind),0);frame();
    assert.equal(count(editKind),1);
    assert.deepEqual(JSON.parse(probe.report()).samples[editKind],[time-editedAt]);
    assert.ok(time-editedAt>=430,'duration includes pre-begin debounce/draft time');
    assert.equal(probe.report().includes('private-note-id'),false,'reports must not retain correlation IDs');
    edit('private-note-id',2);const obsoleteEdit=probe.beginEditorEdit('private-note-id',2);
    edit('private-note-id',3);probe.end(obsoleteEdit,true,guard);frame();frame();assert.equal(count(editKind),1);
    assert.equal(probe.beginEditorEdit('private-note-id',2),0);
    const imeEdit=probe.beginEditorEdit('private-note-id',3);probe.end(imeEdit,true,guard);frame();
    edit('private-note-id',4,true);frame();assert.equal(count(editKind),1);
    assert.equal(probe.beginEditorEdit('private-note-id',4),0,'composing changes are not complete edits');
    edit('private-note-id',5);const imeStart=probe.beginEditorEdit('private-note-id',5);
    listeners.get('compositionstart')({type:'compositionstart',target:new Element()});
    probe.end(imeStart,true,guard);frame();frame();assert.equal(count(editKind),1);
    edit('private-note-id',6);listeners.get('beforeinput')({type:'beforeinput',target:new Element()});
    assert.equal(probe.beginEditorEdit('private-note-id',6),0,'later input invalidates the candidate');
    document.visibilityState='hidden';edit('private-note-id',7);assert.equal(probe.beginEditorEdit('private-note-id',7),0);
    document.visibilityState='visible';assert.equal(probe.beginEditorEdit('private-note-id',7),0,'hidden-origin candidate stays excluded');
    edit('private-note-id',7);document.visibilityState='hidden';listeners.get('visibilitychange')();document.visibilityState='visible';
    assert.equal(probe.beginEditorEdit('private-note-id',7),0,'interrupted foreground candidate cannot return after visibility changes');
    edit('private-note-id',7);focus=false;listeners.get('blur')();focus=true;
    assert.equal(probe.beginEditorEdit('private-note-id',7),0,'blurred candidate cannot return after focus restoration');
    edit('private-note-id',7);const blurredSpan=probe.beginEditorEdit('private-note-id',7);probe.end(blurredSpan,true,guard);
    frame();focus=false;listeners.get('blur')();focus=true;frame();assert.equal(count(editKind),1,'brief blur also invalidates an ending span');
    edit('private-note-id',8);const hiddenEdit=probe.beginEditorEdit('private-note-id',8);
    probe.end(hiddenEdit,true,guard);frame();document.visibilityState='hidden';frame();document.visibilityState='visible';assert.equal(count(editKind),1);
    edit('private-note-id',9);const rejectedEdit=probe.beginEditorEdit('private-note-id',9);
    probe.end(rejectedEdit,false,guard);frame();frame();assert.equal(count(editKind),1);
    edit('private-note-id',10);probe.start();assert.equal(probe.beginEditorEdit('private-note-id',10),0,'restart removes candidate');
    edit('private-note-id',11);const restartEdit=probe.beginEditorEdit('private-note-id',11);
    probe.end(restartEdit,true,guard);frame();probe.start();frame();frame();assert.equal(count(editKind),0);
    const entries=Array.from({length:180005},(_,i)=>({duration:i===180004?501:2}));
    longTasks({getEntries:()=>entries});
    const report=JSON.parse(probe.report(true)),aggregate=report.summary.foregroundLongTask;
    assert.equal(aggregate.count,180005);assert.equal(aggregate.retainedCount,180000);
    assert.equal(aggregate.max,501);assert.equal(aggregate.atLeast200ms,1);
    assert.equal(aggregate.p95Population,'retained-prefix');assert.equal(report.skipped,5);
    assert.equal(listeners.has('grasp-editor-edit'),false,'stop removes its editor listener');
    assert.equal(listeners.has('visibilitychange'),false,'stop removes its visibility listener');
    assert.equal(listeners.has('blur'),false,'stop removes its window focus listener');
    assert.equal(probe.beginEditorEdit('private-note-id',11),0);
  } finally {for(const [key,descriptor]of Object.entries(old))if(descriptor)Object.defineProperty(globalThis,key,descriptor);else delete globalThis[key];}
});
